Update magisk.yml

diff --git a/.github/workflows/magisk.yml b/.github/workflows/magisk.yml
--- a/.github/workflows/magisk.yml
+++ b/.github/workflows/magisk.yml
@@ -68,7 +68,7 @@ jobs:
         id: build_dir
         run: |
           set -euxo pipefail
-          ROOT_DIR="${ROOT_DIR_PREFIX}-$(date +'%Y-%m-%d-%I-%M-%p')-release"
+          ROOT_DIR="${ROOT_DIR_PREFIX}-cabage-release"
           echo "ROOT_DIR=${ROOT_DIR}" >> $GITHUB_ENV
           BUILD_DIR="builds/${ROOT_DIR}"
           echo "BUILD_DIR=${BUILD_DIR}" >> $GITHUB_ENV
@@ -81,7 +81,7 @@ jobs:
           set -euxo pipefail
           git clone --recursive https://github.com/TheWildJames/AnyKernel3.git -b "$BRANCH"
 
-      - name: Setup Kernel Source
+      - name: Setup Kernel Source (Using repo)
         working-directory: ${{ env.BUILD_DIR }}
         run: |
           set -euxo pipefail
@@ -93,14 +93,14 @@ jobs:
 
           sync_attempts=3
           for i in $(seq 1 $sync_attempts); do
-              repo sync -c -j"$(nproc)" --force-sync --no-clone-bundle --no-tags
-              if [ $? -eq 0 ]; then break; fi
+              repo sync -c -j"$(nproc)" --force-sync --no-clone-bundle --no-tags && break
               echo "Repo sync failed. Attempt $i of $sync_attempts"
               if [ $i -lt $sync_attempts ]; then sleep 60; fi
           done
-          [ $? -ne 0 ] && { echo "Repo sync failed after multiple attempts."; exit 1; }
-
+          [ $? -eq 0 ] || { echo "Repo sync failed after multiple attempts."; exit 1; }
           rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*
+          rm -rf ./kernel_platform/msm-kernel/android/abi_gki_protected_exports_*
+          
           #cd kernel_platform
           # Add additional tmpfs config setting
            #echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
